version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracking-frontend
    env_file: .env
    ports:
      - "127.0.0.1:3002:3000"
    restart: unless-stopped
    networks:
      - tracking-network

networks:
  tracking-network:
    external: true
