flowchart LR
    subgraph MCU["ESP32-S3"]
        SCL["GPIO1 - SCL"]
        SDA["GPIO2 - SDA"]
        INT1["GPIO41 - INT1"]
        INT2["GPIO42 - INT2"]
        VCC["3.3V"]
        GND["GND"]
    end

    subgraph IMU["LIS3DSH"]
        I2CSCL["SCL"]
        I2CSDA["SDA"]
        I2CINT1["INT1"]
        I2CINT2["INT2"]
        IVCC["VDD"]
        IGND["GND"]
    end

    SCL ----> I2CSCL
    SDA ----> I2CSDA
    INT1 ----> I2CINT1
    INT2 ----> I2CINT2
    VCC --> IVCC
    GND --> IGND
