%%{init: {'flowchart': {'nodeSpacing': 80, 'rankSpacing': 100}} }%%
flowchart TB
    Boot["Khởi động"]
    IgnOn["Bật IGN"]
    IgnOff["Tắt IGN"]
    Driving["Lái xe"]
    Parking["Đỗ xe"]
    Motion["LIS3DH phát hiện rung"]
    Alert["Cảnh báo"]
    Done["Đã xử lý"]
    Continue["Xe tiếp tục chạy"]
    Stop["Tắt máy"]

    Boot --> IgnOn --> Driving
    Boot --> IgnOff --> Parking
    Driving --> Stop --> Parking
    Parking --> Motion --> Alert
    Alert --> Done --> Parking
    Alert --> Continue --> Driving
