erDiagram
    USERS ||--O{ VEHICLES : quản_lý
    VEHICLES ||--O{ DEVICES : gắn
    VEHICLES ||--O{ TRIPS : phát_sinh
    TRIPS ||--O{ TRIP_EVENTS : gồm
    VEHICLES ||--O{ ALERTS : tạo_ra
    DEVICES ||--o{ COMMANDS : nhận

    USERS {
      uuid id
      string email
      string role
    }
    VEHICLES {
      uuid id
      string license_plate
      string status
    }
    DEVICES {
      uuid id
      string serial
      string imei
    }
