flowchart TB
    MCU["ESP32-S3"]

    Source["Nguồn xe 12V/24V"] --> ADC["GPIO3 ADC<br/>U_SUPPLY"] --> MCU
    Backup["Pin dự phòng 18650"] --> BADC["GPIO4 ADC<br/>U_BATT"] --> MCU

    MCU --> Modem["SIM7600CE-T<br/>UART1 GPIO17/18<br/>PWRKEY GPIO34 + RESET GPIO35<br/>Rail ~4V modem"]
    MCU --> I2C["I2C0<br/>SDA GPIO2 / SCL GPIO1"]
    I2C --> IMU["LIS3DH<br/>INT1 GPIO41"]
    I2C --> RTC["DS3231M"]
    MCU -. BLE .-> OBD["vgate iCar Pro<br/>OBD2 BLE"]
    MCU --> Storage["microSD<br/>SDMMC GPIO7-13"]
    MCU --> Logic["Máy trạng thái"]
