flowchart TB
    Power["Nguon chinh 12V/24V<br/>+ pin du phong"]
    MCU["ESP32-S3 + Power FSM"]
    Modem["SIM7600CE-T<br/>4G + GNSS"]
    OBD["OBD2 BLE"]
    IMU["LIS3DSH"]
    Cloud["MQTT / Cloud"]

    Power --> MCU
    MCU --> Modem --> Cloud
    MCU --> OBD
    MCU --> IMU
