xychart-beta
    title "Dòng tiêu thụ theo các pha vận hành chính"
    x-axis ["Chạy", "Phát tin", "Chờ", "Đỗ", "Ngủ sâu", "Cảnh báo", "Ổn định"]
    y-axis "mA" 0 --> 450
    line [350, 360, 180, 15, 1, 380, 15]
