xychart-beta
    title "Thời gian bắt vệ tinh GPS"
    x-axis ["Nguội-Min", "Nguội-TB", "Nguội-Max", "Ấm-Min", "Ấm-TB", "Ấm-Max", "Nóng-Min", "Nóng-TB", "Nóng-Max"]
    y-axis "Giây" 0 --> 65
    bar [20, 30, 60, 3, 5, 12, 1, 2, 3]