---
config:
  themeVariables:
    xyChart:
      plotColorPalette: "#FFA07A"
---
xychart-beta
    title "Mức đáp ứng so với mục tiêu thiết kế"
    x-axis ["Định vị", "Độ trễ", "Ổn định", "Tiết kiệm điện", "Giao diện", "Dữ liệu xe"]
    y-axis "Tỷ lệ đạt (%)" 0 --> 100
    bar [98, 94, 98, 98, 96, 96]
