---
config:
  xyChart:
    showDataLabel: true
    showDataLabelOutsideBar: true
  themeVariables:
    xyChart:
      plotColorPalette: "#FFA07A"
---
xychart-beta
    title "Thời gian lấy lại vị trí theo trạng thái khởi động"
    x-axis ["Cold Start\n(khởi động từ trạng thái chưa có dữ liệu vệ tinh gần trước đó)", "Warm Start\n(khởi động khi còn giữ một phần dữ liệu hỗ trợ)", "Hot Start\n(khởi động khi vẫn còn dữ liệu hỗ trợ và thời gian gần đúng)"]
    y-axis "Giây" 0 --> 35
    bar [30, 5, 2]
