xychart-beta
    title "Dòng tiêu thụ theo chu kỳ hoạt động"
    x-axis ["Drive0", "Drive5", "Idle10", "Sleep20", "Deep25", "Alert32", "Park40"]
    y-axis "mA" 0 --> 450
    line [350, 360, 180, 15, 1, 380, 15]
