xychart-beta
    title "Dòng tiêu thụ theo chu kỳ hoạt động"
    x-axis ["Chạy-0", "Chạy-5", "Chờ-10", "Ngủ-20", "Ngủ sâu-25", "Cảnh báo-32", "Đỗ xe-40"]
    y-axis "mA" 0 --> 450
    line [350, 360, 180, 15, 1, 380, 15]