---
config:
  xyChart:
    showDataLabel: true
    showDataLabelOutsideBar: true
  themeVariables:
    xyChart:
      plotColorPalette: "#FFA07A"
---
xychart-beta
    title "Các phần tạo nên độ trễ toàn tuyến"
    x-axis ["Mạng", "Tiếp nhận", "Lưu trữ", "Cảnh báo", "Màn hình", "Toàn tuyến"]
    y-axis "ms" 0 --> 220
    bar [150, 5, 10, 5, 15, 185]
