services:
  backend:
    image: ${DOCKERHUB_USERNAME}/tracking-backend:uat
    container_name: tracking-backend
    ports:
      - '4000:4000'
    env_file: .env
    environment:
      MQTT_LISTENER_CLIENT_ID: tracking-backend-listener
    restart: always
    volumes:
      - ../Tracking_Data/Tracking_Backend/firmware:/app/firmware
    networks:
      - tracking-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

networks:
  tracking-network:
    external: true
