import {
    IconLayoutDashboard,
    IconCar,
    IconUsers,
    IconRoute,
    IconBell,
    IconAlertTriangle,
    IconMapPin,
    IconDeviceDesktop,
    IconTool,
    IconSettings,
    IconMap,
    IconLogout,
    IconUserCircle,
    IconChevronRight,
    IconChevronsUpDown,
    IconMenu2,
    IconX,
    IconSun,
    IconMoon,
    IconPlus,
    IconSearch,
    IconFilter,
    IconRefresh,
    IconEdit,
    IconTrash,
    IconEye,
    IconCheck,
    IconLoader2,
} from '@tabler/icons-react';

export const Icons = {
    logo: IconCar,
    dashboard: IconLayoutDashboard,
    car: IconCar,
    users: IconUsers,
    route: IconRoute,
    bell: IconBell,
    alertTriangle: IconAlertTriangle,
    mapPin: IconMapPin,
    device: IconDeviceDesktop,
    tool: IconTool,
    settings: IconSettings,
    map: IconMap,
    logout: IconLogout,
    user: IconUserCircle,
    chevronRight: IconChevronRight,
    chevronsUpDown: IconChevronsUpDown,
    menu: IconMenu2,
    close: IconX,
    sun: IconSun,
    moon: IconMoon,
    plus: IconPlus,
    search: IconSearch,
    filter: IconFilter,
    refresh: IconRefresh,
    edit: IconEdit,
    trash: IconTrash,
    eye: IconEye,
    check: IconCheck,
    spinner: IconLoader2,
} as const;

export type IconName = keyof typeof Icons;

export function getIcon(name: string) {
    return Icons[name as IconName] || Icons.logo;
}
