stateDiagram-v2
    direction LR
    [*] --> Parking
    state "Parking
Deep sleep" as Parking
    state "Driving
4G + GNSS + OBD2" as Driving
    state "Alert
Đánh thức modem" as Alert

    Parking --> Driving: Bật IGN
    Driving --> Parking: Tắt IGN
    Parking --> Alert: IMU rung
    Alert --> Parking: Hoàn tất
    Alert --> Driving: Xe tiếp tục chạy
