#pragma once

#include "driver/gpio.h"
#include "driver/uart.h"

#define PIN_IGN_IN GPIO_NUM_2
#define PIN_U_BATT_ADC GPIO_NUM_4
#define PIN_CHARGER_EN GPIO_NUM_5
#define PIN_MODEM_TX GPIO_NUM_16
#define PIN_MODEM_RX GPIO_NUM_17
#define PIN_POWER_MUX_SEL GPIO_NUM_18
#define PIN_LVD_STATUS GPIO_NUM_19
#define PIN_LIS3DH_INT GPIO_NUM_21
#define PIN_LIS3DH_SDA GPIO_NUM_22
#define PIN_LIS3DH_SCL GPIO_NUM_23
#define PIN_MODEM_PWRKEY GPIO_NUM_25

#define MODEM_UART_NUM UART_NUM_1
#define MODEM_UART_BAUD 115200
