import { Router } from 'express';
import authRoutes from '@/api/routes/auth.routes';
import deviceRoutes from '@/api/routes/device.routes';
import dashboardRoutes from '@/api/routes/dashboard.routes';
import firmwareRoutes from '@/api/routes/firmware.routes';
import exportRoutes from '@/api/routes/export.routes';
import systemAdminRoutes from '@/api/routes/system-admin.routes';
import vehicleRoutes from '@/api/routes/vehicle.routes';
import customerRoutes from '@/api/routes/customer.routes';
import tripRoutes from '@/api/routes/trip.routes';
import alertRoutes from '@/api/routes/alert.routes';
import geofenceRoutes from '@/api/routes/geofence.routes';
import maintenanceRoutes from '@/api/routes/maintenance.routes';
import usersRoutes from '@/api/routes/users.routes';
import statisticsRoutes from '@/api/routes/statistics.routes';
import notificationsRoutes from '@/api/routes/notifications.routes';
import healthRoutes from '@/api/routes/health.routes';
import iotRoutes from '@/api/routes/iot.routes';
import telemetryRoutes from '@/api/routes/telemetry.routes';
import simulatorRoutes from '@/api/routes/simulator.routes';
import systemRoutes from '@/api/routes/system.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/iot', iotRoutes);
router.use('/device', deviceRoutes);
router.use('/devices', deviceRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/firmware', firmwareRoutes);
router.use('/exports', exportRoutes);
router.use('/export', exportRoutes);
router.use('/system-admin', systemAdminRoutes);
router.use('/vehicles', vehicleRoutes);
router.use('/customers', customerRoutes);
router.use('/trips', tripRoutes);
router.use('/alerts', alertRoutes);
router.use('/geofences', geofenceRoutes);
router.use('/maintenance', maintenanceRoutes);
router.use('/stats', statisticsRoutes);
router.use('/statistics', statisticsRoutes);
router.use('/telemetry', telemetryRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/simulator', simulatorRoutes);
router.use('/system', systemRoutes);
router.use('/health', healthRoutes);

export default router;
